### ISSUE TITLE
update/ install failed 2.2.2 

### ISSUE THREAD

**Issue by katchy3132** [jjw24/Wox.Plugin.Runner#16]
I updated from 2.2.0 to 2.2.2 and got this message. Plugin is now not listed as installed. 
I also get this message when I try to install from scratch . 
Basicly it wont install now. 

![image](https://user-images.githubusercontent.com/3707138/108627537-c709fb00-745e-11eb-8f87-768f4d6b9698.png)

**Comment by jjw24** [comment]
Update to 2.2.3 should fix this issue
