### ISSUE TITLE
Program does not execute unless shortcut is fully completed

### ISSUE THREAD

**Issue by accelyte** [jjw24/Wox.Plugin.Runner#18]
I have a shortcut setup like so:
![Flow Launcher_kM8E9c5YAj](https://user-images.githubusercontent.com/95587932/164191786-38b90a62-cfcd-4487-9512-af3aace2c5d0.png)

If I hit `Enter` before the shortcut is completed, e.g.:
![egDlQv0jw7](https://user-images.githubusercontent.com/95587932/164191989-e2fb0422-8e35-4dc8-b3db-6f6ab7b5da3e.png)

Instead of running the program, the shortcut gets autocompleted, but with an asterisk in the front:
![uO0koEetsv](https://user-images.githubusercontent.com/95587932/164192350-381dc72e-8a18-4d65-9e24-a1b25e41d2a3.png)

However, if I type the full shortcut, then the program runs just fine, e.g.:
![ET5nOAE3Bb](https://user-images.githubusercontent.com/95587932/164192403-bf6e3ece-7ce7-408a-8f53-ea20dc046aa1.png)

I would normally expect the shortcut to run even if it isn't completed.

Edit: changing the action keyword from `*` to something else (e.g. `r`) does not seem to change the behaviour, I have to type the entire command with the action keyword included (i.e. `r arknights`)

**Comment by jjw24** [comment]
Just to confirm the behaviour, when you have your action keyword as `r` and you type `r ark`, hit enter, it will auto complete and hit enter again it will actually open arknights, is this the behaviour you are getting?

**Comment by accelyte** [comment]
No, `r ark + Enter` results in `* arknights`, the same as the 2nd result screenshot.

**Comment by jjw24** [comment]
In your first screenshot you have action keyword as `*`, did you change it to `r` when you tested it like I mentioned?

**Comment by accelyte** [comment]
Yes, I did, see the edit in my initial comment.

**Comment by jjw24** [comment]
Yeah I can see the issue why the `*` shows up which shouldn't https://github.com/jjw24/Wox.Plugin.Runner/blob/eb3e4b3bb8af460ff4872c7b25b14b3f2387ceb2/Wox.Plugin.Runner/Runner.cs#L86.

Will put through a fix.

**Comment by jjw24** [comment]
I might also take the opportunity to drop the autocomplete part which shouldn't be needed, causing to press enter twice to launch the result.

**Comment by dennisvtang** [comment]
I believe I've fixed this issue and have removed the need to press enter twice to launch suggested commands with PR #20. 

I would appreciate it if someone else could test it and review it as C# isn't a langauge I program much in.
