### ISSUE TITLE
Help - passing arguments

### ISSUE THREAD

**Issue by 133501** [jjw24/Wox.Plugin.Runner#19]
Hello,
I'm very much a programing noob but I'm trying to take advantage of your plugin.
Can you please help me, or give me a hint?

What I'm trying to do:
 - end task is to edit a note file inside the Obsidian note-taking app using Obsidians [URI](https://help.obsidian.md/Advanced+topics/Using+obsidian+URI)
 - within the plugin setting I'm trying to use my Shortcut and Argument to append the argument to the note

What I'm able to do:
 - by adding `obsidian://new?vault=my%20vault&name=my%20note&content=test-append&append` to Path in the plugins setting I'm able to do what this command is supposed to do - open `my vault` and create `my note` inside of which I'm able to append text `test-append`

What I'm struggling with:
 - create the URI link in a way that it would take the arguments and place them in link as: `content=ARGUMENT` 
 
Then I could do something like `r o ARGUMENT` in flow.launcher which would produce the URI link as: `obsidian://new?vault=my%20vault&name=my%20note&content=ARGUMENT&append`

Thank you in advance.
Tomas

**Comment by jjw24** [comment]
Hi there, this plugin is currently not designed to work this way.

@Garulf is this something that can be added to Obsidian plugin instead?

**Comment by jjw24** [comment]
hey @133501, as a work around, the pre-release version of Flow supports running app URI via the WebSearch plugin. You can download it [here](https://github.com/Flow-Launcher/Flow.Launcher/discussions/956) and then set it up like the following:
 
![image](https://user-images.githubusercontent.com/26427004/170819463-30c89a55-7c7e-42e7-af9e-f61d33d4946a.png)

URL: `obsidian://new?vault=my%20vault&name=my%20note&content={q}&append`

and then run it like:
`ob test-append`
where {q} is the parameter. 

Give it a try, let me know how you go.

**Comment by 133501** [comment]
hi @jjw24!
Thank you very much for pointing this out to me! It does work as expected :)
I'm looking forward to the normal release of this feature.

If there was an option to add a second argument it would be heaven - e.g. for passing a note name. But I understand, that is kinda one app specific feature. Maybe a specific plugin is a better way to go.

Thank you!

**Comment by jjw24** [comment]
> If there was an option to add a second argument it would be heaven

Unfortunately that won't be possible. 

Yeah this functionality better off added via the Obsidian plugin, however bear mind though even when it is added, will probably just support simple text/sentences, anything more complex will be better off doing it in the actual Obsidian editor.

Have you tried just using the Obsidian plugin? Might be faster just launching the note via the plugin and work directly in the Obsidian editor?

**Comment by 133501** [comment]
> ....will be better off doing it in the actual Obsidian editor.

Absolutely. I'll try to reach out to the Obsidian community if there are some willing people with the right skill set. 
 
> Have you tried just using the Obsidian plugin? Might be faster just launching the note via the plugin and work directly in the Obsidian editor?

If you think this [Obsidian Plugin](https://github.com/Garulf/obsidian-notes) from Garulf then no, it is just to search in notes.

**Comment by jjw24** [comment]
> Obsidian editor?
If you think this Obsidian Plugin from Garulf then no, it is just to search in notes.

Yeah it searches then can launch the note in the Obsidian editor if I am not mistaken, which you can then continue to update the note.

**Comment by jjw24** [comment]
>If there was an option to add a second argument it would be heaven - e.g. for passing a note name. But I understand, that is kinda one app specific feature. Maybe a specific plugin is a better way to go.

This should be supported already.
