### ISSUE TITLE
Arguments not working

### ISSUE THREAD

**Issue by giggio** [jjw24/Wox.Plugin.Runner#3]
When you set an argument and run it the first time the app is ran without the argument. In the second time it crashes Flow Launcher.

My settings:
Shortcut: n
Path: C:\WINDOWS\system32\notepad.exe
Arguments: c:\temp\file.txt

The behavior is consistent on my machine. It always crashes the second time.
I tried setting the description and/or work dir, it made no difference.

**Comment by knightofnet** [comment]
Hi, same problem appears to me.

I've try this settings for an entry ;
Shortcut: r
Path: "C:\Program Files\Malwarebytes\Windows Firewall Control\wfc.exe"
Wd: "C:\Program Files\Malwarebytes\Windows Firewall Control\"
Arguments: -cp

**Comment by jjw24** [comment]
Strange, will take a look soon

**Comment by jjw24** [comment]
This will be fixed in release 2.0.2
