### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by Hsayrey** [jjw24/Wox.Plugin.Runner#38]
I would like to use this plugin but this is not open source and my company will not allow us unless this is open source. Can we make this project open source?

**Comment by jjw24** [comment]
Hi there, this plugin is open source and is MIT licensed. Perhaps find out from your company what's the reason for thinking this is not.

**Comment by Hsayrey** [comment]
Correct, no idea why this failed approval. Will re-reach out. Thanks!
