### ISSUE TITLE
System.Text.Json.JsonException

### ISSUE THREAD

**Issue by jjw24** [jjw24/Wox.Plugin.Runner#9]
![image](https://user-images.githubusercontent.com/26427004/107933074-6730d180-6fd2-11eb-8ef1-4a5927fde63b.png)

@taooceros Is this error related to the json change?

**Comment by taooceros** [comment]
Oh I believe it will throw the error when the string is empty.

**Comment by taooceros** [comment]
Found an issue, that we should move the command.json to LocalAppdata to avoid deleting when update. However, it is still in appdata now. The pluginmetadata.plugindirectory seems to be the path for the place storing the dll.

We need to change that to `%appdata%\FlowLauncher\Settings\Plugins\{PluginName}`
